// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sidescansource.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sidescansource_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sidescansource_2eproto
#define PROTOBUF_USE_DLLS
#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sidescansource_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sidescansource_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sidescansource_2eproto;
class CruiseRouteSource;
struct CruiseRouteSourceDefaultTypeInternal;
extern CruiseRouteSourceDefaultTypeInternal _CruiseRouteSource_default_instance_;
class CruiseRouteSourceList;
struct CruiseRouteSourceListDefaultTypeInternal;
extern CruiseRouteSourceListDefaultTypeInternal _CruiseRouteSourceList_default_instance_;
class SideScanSource;
struct SideScanSourceDefaultTypeInternal;
extern SideScanSourceDefaultTypeInternal _SideScanSource_default_instance_;
class SideScanSourceList;
struct SideScanSourceListDefaultTypeInternal;
extern SideScanSourceListDefaultTypeInternal _SideScanSourceList_default_instance_;
class StatusResponse;
struct StatusResponseDefaultTypeInternal;
extern StatusResponseDefaultTypeInternal _StatusResponse_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CruiseRouteSource* Arena::CreateMaybeMessage<::CruiseRouteSource>(Arena*);
template<> ::CruiseRouteSourceList* Arena::CreateMaybeMessage<::CruiseRouteSourceList>(Arena*);
template<> ::SideScanSource* Arena::CreateMaybeMessage<::SideScanSource>(Arena*);
template<> ::SideScanSourceList* Arena::CreateMaybeMessage<::SideScanSourceList>(Arena*);
template<> ::StatusResponse* Arena::CreateMaybeMessage<::StatusResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class SideScanSource final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SideScanSource) */ {
 public:
  inline SideScanSource() : SideScanSource(nullptr) {}
  ~SideScanSource() override;
  explicit PROTOBUF_CONSTEXPR SideScanSource(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SideScanSource(const SideScanSource& from);
  SideScanSource(SideScanSource&& from) noexcept
    : SideScanSource() {
    *this = ::std::move(from);
  }

  inline SideScanSource& operator=(const SideScanSource& from) {
    CopyFrom(from);
    return *this;
  }
  inline SideScanSource& operator=(SideScanSource&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SideScanSource& default_instance() {
    return *internal_default_instance();
  }
  static inline const SideScanSource* internal_default_instance() {
    return reinterpret_cast<const SideScanSource*>(
               &_SideScanSource_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SideScanSource& a, SideScanSource& b) {
    a.Swap(&b);
  }
  inline void Swap(SideScanSource* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SideScanSource* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SideScanSource* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SideScanSource>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SideScanSource& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SideScanSource& from) {
    SideScanSource::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SideScanSource* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SideScanSource";
  }
  protected:
  explicit SideScanSource(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kComputerTimeFieldNumber = 2,
    kDtTimeFieldNumber = 3,
    kHorizontalRangeDirectionFieldNumber = 7,
    kSideScanImageNameFieldNumber = 11,
    kRemarksFieldNumber = 14,
    kVerifyImagePathsFieldNumber = 17,
    kImageDescriptionFieldNumber = 18,
    kCruiseNumberFieldNumber = 22,
    kDiveNumberFieldNumber = 23,
    kLongitudeFieldNumber = 4,
    kLatitudeFieldNumber = 5,
    kDtSpeedFieldNumber = 6,
    kHorizontalRangeValueFieldNumber = 8,
    kHeightFromBottomFieldNumber = 9,
    kRTheatFieldNumber = 10,
    kAlongTrackFieldNumber = 12,
    kAcrossTrackFieldNumber = 13,
    kSupposeSizeFieldNumber = 15,
    kPriorityFieldNumber = 16,
    kTargetLongitudeFieldNumber = 19,
    kTargetLatitudeFieldNumber = 20,
    kPositionErrorFieldNumber = 21,
    kStatusFieldNumber = 24,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string computer_time = 2;
  void clear_computer_time();
  const std::string& computer_time() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_computer_time(ArgT0&& arg0, ArgT... args);
  std::string* mutable_computer_time();
  PROTOBUF_NODISCARD std::string* release_computer_time();
  void set_allocated_computer_time(std::string* computer_time);
  private:
  const std::string& _internal_computer_time() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_computer_time(const std::string& value);
  std::string* _internal_mutable_computer_time();
  public:

  // string dt_time = 3;
  void clear_dt_time();
  const std::string& dt_time() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_dt_time(ArgT0&& arg0, ArgT... args);
  std::string* mutable_dt_time();
  PROTOBUF_NODISCARD std::string* release_dt_time();
  void set_allocated_dt_time(std::string* dt_time);
  private:
  const std::string& _internal_dt_time() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_dt_time(const std::string& value);
  std::string* _internal_mutable_dt_time();
  public:

  // string horizontal_range_direction = 7;
  void clear_horizontal_range_direction();
  const std::string& horizontal_range_direction() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_horizontal_range_direction(ArgT0&& arg0, ArgT... args);
  std::string* mutable_horizontal_range_direction();
  PROTOBUF_NODISCARD std::string* release_horizontal_range_direction();
  void set_allocated_horizontal_range_direction(std::string* horizontal_range_direction);
  private:
  const std::string& _internal_horizontal_range_direction() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_horizontal_range_direction(const std::string& value);
  std::string* _internal_mutable_horizontal_range_direction();
  public:

  // string side_scan_image_name = 11;
  void clear_side_scan_image_name();
  const std::string& side_scan_image_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_side_scan_image_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_side_scan_image_name();
  PROTOBUF_NODISCARD std::string* release_side_scan_image_name();
  void set_allocated_side_scan_image_name(std::string* side_scan_image_name);
  private:
  const std::string& _internal_side_scan_image_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_side_scan_image_name(const std::string& value);
  std::string* _internal_mutable_side_scan_image_name();
  public:

  // string remarks = 14;
  void clear_remarks();
  const std::string& remarks() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_remarks(ArgT0&& arg0, ArgT... args);
  std::string* mutable_remarks();
  PROTOBUF_NODISCARD std::string* release_remarks();
  void set_allocated_remarks(std::string* remarks);
  private:
  const std::string& _internal_remarks() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_remarks(const std::string& value);
  std::string* _internal_mutable_remarks();
  public:

  // string verify_image_paths = 17;
  void clear_verify_image_paths();
  const std::string& verify_image_paths() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_verify_image_paths(ArgT0&& arg0, ArgT... args);
  std::string* mutable_verify_image_paths();
  PROTOBUF_NODISCARD std::string* release_verify_image_paths();
  void set_allocated_verify_image_paths(std::string* verify_image_paths);
  private:
  const std::string& _internal_verify_image_paths() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_verify_image_paths(const std::string& value);
  std::string* _internal_mutable_verify_image_paths();
  public:

  // string image_description = 18;
  void clear_image_description();
  const std::string& image_description() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_image_description(ArgT0&& arg0, ArgT... args);
  std::string* mutable_image_description();
  PROTOBUF_NODISCARD std::string* release_image_description();
  void set_allocated_image_description(std::string* image_description);
  private:
  const std::string& _internal_image_description() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_image_description(const std::string& value);
  std::string* _internal_mutable_image_description();
  public:

  // string cruise_number = 22;
  void clear_cruise_number();
  const std::string& cruise_number() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_cruise_number(ArgT0&& arg0, ArgT... args);
  std::string* mutable_cruise_number();
  PROTOBUF_NODISCARD std::string* release_cruise_number();
  void set_allocated_cruise_number(std::string* cruise_number);
  private:
  const std::string& _internal_cruise_number() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cruise_number(const std::string& value);
  std::string* _internal_mutable_cruise_number();
  public:

  // string dive_number = 23;
  void clear_dive_number();
  const std::string& dive_number() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_dive_number(ArgT0&& arg0, ArgT... args);
  std::string* mutable_dive_number();
  PROTOBUF_NODISCARD std::string* release_dive_number();
  void set_allocated_dive_number(std::string* dive_number);
  private:
  const std::string& _internal_dive_number() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_dive_number(const std::string& value);
  std::string* _internal_mutable_dive_number();
  public:

  // double longitude = 4;
  void clear_longitude();
  double longitude() const;
  void set_longitude(double value);
  private:
  double _internal_longitude() const;
  void _internal_set_longitude(double value);
  public:

  // double latitude = 5;
  void clear_latitude();
  double latitude() const;
  void set_latitude(double value);
  private:
  double _internal_latitude() const;
  void _internal_set_latitude(double value);
  public:

  // float dt_speed = 6;
  void clear_dt_speed();
  float dt_speed() const;
  void set_dt_speed(float value);
  private:
  float _internal_dt_speed() const;
  void _internal_set_dt_speed(float value);
  public:

  // float horizontal_range_value = 8;
  void clear_horizontal_range_value();
  float horizontal_range_value() const;
  void set_horizontal_range_value(float value);
  private:
  float _internal_horizontal_range_value() const;
  void _internal_set_horizontal_range_value(float value);
  public:

  // float height_from_bottom = 9;
  void clear_height_from_bottom();
  float height_from_bottom() const;
  void set_height_from_bottom(float value);
  private:
  float _internal_height_from_bottom() const;
  void _internal_set_height_from_bottom(float value);
  public:

  // float r_theat = 10;
  void clear_r_theat();
  float r_theat() const;
  void set_r_theat(float value);
  private:
  float _internal_r_theat() const;
  void _internal_set_r_theat(float value);
  public:

  // float along_track = 12;
  void clear_along_track();
  float along_track() const;
  void set_along_track(float value);
  private:
  float _internal_along_track() const;
  void _internal_set_along_track(float value);
  public:

  // float across_track = 13;
  void clear_across_track();
  float across_track() const;
  void set_across_track(float value);
  private:
  float _internal_across_track() const;
  void _internal_set_across_track(float value);
  public:

  // float suppose_size = 15;
  void clear_suppose_size();
  float suppose_size() const;
  void set_suppose_size(float value);
  private:
  float _internal_suppose_size() const;
  void _internal_set_suppose_size(float value);
  public:

  // uint32 priority = 16;
  void clear_priority();
  uint32_t priority() const;
  void set_priority(uint32_t value);
  private:
  uint32_t _internal_priority() const;
  void _internal_set_priority(uint32_t value);
  public:

  // double target_longitude = 19;
  void clear_target_longitude();
  double target_longitude() const;
  void set_target_longitude(double value);
  private:
  double _internal_target_longitude() const;
  void _internal_set_target_longitude(double value);
  public:

  // double target_latitude = 20;
  void clear_target_latitude();
  double target_latitude() const;
  void set_target_latitude(double value);
  private:
  double _internal_target_latitude() const;
  void _internal_set_target_latitude(double value);
  public:

  // float position_error = 21;
  void clear_position_error();
  float position_error() const;
  void set_position_error(float value);
  private:
  float _internal_position_error() const;
  void _internal_set_position_error(float value);
  public:

  // uint32 status = 24;
  void clear_status();
  uint32_t status() const;
  void set_status(uint32_t value);
  private:
  uint32_t _internal_status() const;
  void _internal_set_status(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SideScanSource)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr computer_time_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dt_time_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr horizontal_range_direction_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr side_scan_image_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr remarks_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr verify_image_paths_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_description_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cruise_number_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dive_number_;
    double longitude_;
    double latitude_;
    float dt_speed_;
    float horizontal_range_value_;
    float height_from_bottom_;
    float r_theat_;
    float along_track_;
    float across_track_;
    float suppose_size_;
    uint32_t priority_;
    double target_longitude_;
    double target_latitude_;
    float position_error_;
    uint32_t status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sidescansource_2eproto;
};
// -------------------------------------------------------------------

class SideScanSourceList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SideScanSourceList) */ {
 public:
  inline SideScanSourceList() : SideScanSourceList(nullptr) {}
  ~SideScanSourceList() override;
  explicit PROTOBUF_CONSTEXPR SideScanSourceList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SideScanSourceList(const SideScanSourceList& from);
  SideScanSourceList(SideScanSourceList&& from) noexcept
    : SideScanSourceList() {
    *this = ::std::move(from);
  }

  inline SideScanSourceList& operator=(const SideScanSourceList& from) {
    CopyFrom(from);
    return *this;
  }
  inline SideScanSourceList& operator=(SideScanSourceList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SideScanSourceList& default_instance() {
    return *internal_default_instance();
  }
  static inline const SideScanSourceList* internal_default_instance() {
    return reinterpret_cast<const SideScanSourceList*>(
               &_SideScanSourceList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SideScanSourceList& a, SideScanSourceList& b) {
    a.Swap(&b);
  }
  inline void Swap(SideScanSourceList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SideScanSourceList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SideScanSourceList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SideScanSourceList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SideScanSourceList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SideScanSourceList& from) {
    SideScanSourceList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SideScanSourceList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SideScanSourceList";
  }
  protected:
  explicit SideScanSourceList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kListFieldNumber = 1,
  };
  // repeated .SideScanSource list = 1;
  int list_size() const;
  private:
  int _internal_list_size() const;
  public:
  void clear_list();
  ::SideScanSource* mutable_list(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SideScanSource >*
      mutable_list();
  private:
  const ::SideScanSource& _internal_list(int index) const;
  ::SideScanSource* _internal_add_list();
  public:
  const ::SideScanSource& list(int index) const;
  ::SideScanSource* add_list();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SideScanSource >&
      list() const;

  // @@protoc_insertion_point(class_scope:SideScanSourceList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SideScanSource > list_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sidescansource_2eproto;
};
// -------------------------------------------------------------------

class StatusResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:StatusResponse) */ {
 public:
  inline StatusResponse() : StatusResponse(nullptr) {}
  ~StatusResponse() override;
  explicit PROTOBUF_CONSTEXPR StatusResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StatusResponse(const StatusResponse& from);
  StatusResponse(StatusResponse&& from) noexcept
    : StatusResponse() {
    *this = ::std::move(from);
  }

  inline StatusResponse& operator=(const StatusResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline StatusResponse& operator=(StatusResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StatusResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const StatusResponse* internal_default_instance() {
    return reinterpret_cast<const StatusResponse*>(
               &_StatusResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(StatusResponse& a, StatusResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(StatusResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StatusResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StatusResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StatusResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StatusResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StatusResponse& from) {
    StatusResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StatusResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "StatusResponse";
  }
  protected:
  explicit StatusResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // bool status = 1;
  void clear_status();
  bool status() const;
  void set_status(bool value);
  private:
  bool _internal_status() const;
  void _internal_set_status(bool value);
  public:

  // @@protoc_insertion_point(class_scope:StatusResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    bool status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sidescansource_2eproto;
};
// -------------------------------------------------------------------

class CruiseRouteSource final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CruiseRouteSource) */ {
 public:
  inline CruiseRouteSource() : CruiseRouteSource(nullptr) {}
  ~CruiseRouteSource() override;
  explicit PROTOBUF_CONSTEXPR CruiseRouteSource(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CruiseRouteSource(const CruiseRouteSource& from);
  CruiseRouteSource(CruiseRouteSource&& from) noexcept
    : CruiseRouteSource() {
    *this = ::std::move(from);
  }

  inline CruiseRouteSource& operator=(const CruiseRouteSource& from) {
    CopyFrom(from);
    return *this;
  }
  inline CruiseRouteSource& operator=(CruiseRouteSource&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CruiseRouteSource& default_instance() {
    return *internal_default_instance();
  }
  static inline const CruiseRouteSource* internal_default_instance() {
    return reinterpret_cast<const CruiseRouteSource*>(
               &_CruiseRouteSource_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(CruiseRouteSource& a, CruiseRouteSource& b) {
    a.Swap(&b);
  }
  inline void Swap(CruiseRouteSource* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CruiseRouteSource* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CruiseRouteSource* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CruiseRouteSource>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CruiseRouteSource& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CruiseRouteSource& from) {
    CruiseRouteSource::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CruiseRouteSource* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CruiseRouteSource";
  }
  protected:
  explicit CruiseRouteSource(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCruiseFieldNumber = 1,
    kTypeFieldNumber = 2,
    kNameFieldNumber = 3,
  };
  // string cruise = 1;
  void clear_cruise();
  const std::string& cruise() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_cruise(ArgT0&& arg0, ArgT... args);
  std::string* mutable_cruise();
  PROTOBUF_NODISCARD std::string* release_cruise();
  void set_allocated_cruise(std::string* cruise);
  private:
  const std::string& _internal_cruise() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cruise(const std::string& value);
  std::string* _internal_mutable_cruise();
  public:

  // string type = 2;
  void clear_type();
  const std::string& type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* type);
  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(const std::string& value);
  std::string* _internal_mutable_type();
  public:

  // string name = 3;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:CruiseRouteSource)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cruise_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sidescansource_2eproto;
};
// -------------------------------------------------------------------

class CruiseRouteSourceList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CruiseRouteSourceList) */ {
 public:
  inline CruiseRouteSourceList() : CruiseRouteSourceList(nullptr) {}
  ~CruiseRouteSourceList() override;
  explicit PROTOBUF_CONSTEXPR CruiseRouteSourceList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CruiseRouteSourceList(const CruiseRouteSourceList& from);
  CruiseRouteSourceList(CruiseRouteSourceList&& from) noexcept
    : CruiseRouteSourceList() {
    *this = ::std::move(from);
  }

  inline CruiseRouteSourceList& operator=(const CruiseRouteSourceList& from) {
    CopyFrom(from);
    return *this;
  }
  inline CruiseRouteSourceList& operator=(CruiseRouteSourceList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CruiseRouteSourceList& default_instance() {
    return *internal_default_instance();
  }
  static inline const CruiseRouteSourceList* internal_default_instance() {
    return reinterpret_cast<const CruiseRouteSourceList*>(
               &_CruiseRouteSourceList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(CruiseRouteSourceList& a, CruiseRouteSourceList& b) {
    a.Swap(&b);
  }
  inline void Swap(CruiseRouteSourceList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CruiseRouteSourceList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CruiseRouteSourceList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CruiseRouteSourceList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CruiseRouteSourceList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CruiseRouteSourceList& from) {
    CruiseRouteSourceList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CruiseRouteSourceList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CruiseRouteSourceList";
  }
  protected:
  explicit CruiseRouteSourceList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kListFieldNumber = 1,
  };
  // repeated .CruiseRouteSource list = 1;
  int list_size() const;
  private:
  int _internal_list_size() const;
  public:
  void clear_list();
  ::CruiseRouteSource* mutable_list(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CruiseRouteSource >*
      mutable_list();
  private:
  const ::CruiseRouteSource& _internal_list(int index) const;
  ::CruiseRouteSource* _internal_add_list();
  public:
  const ::CruiseRouteSource& list(int index) const;
  ::CruiseRouteSource* add_list();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CruiseRouteSource >&
      list() const;

  // @@protoc_insertion_point(class_scope:CruiseRouteSourceList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CruiseRouteSource > list_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sidescansource_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SideScanSource

// string id = 1;
inline void SideScanSource::clear_id() {
  _impl_.id_.ClearToEmpty();
}
inline const std::string& SideScanSource::id() const {
  // @@protoc_insertion_point(field_get:SideScanSource.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SideScanSource::set_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SideScanSource.id)
}
inline std::string* SideScanSource::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:SideScanSource.id)
  return _s;
}
inline const std::string& SideScanSource::_internal_id() const {
  return _impl_.id_.Get();
}
inline void SideScanSource::_internal_set_id(const std::string& value) {
  
  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* SideScanSource::_internal_mutable_id() {
  
  return _impl_.id_.Mutable(GetArenaForAllocation());
}
inline std::string* SideScanSource::release_id() {
  // @@protoc_insertion_point(field_release:SideScanSource.id)
  return _impl_.id_.Release();
}
inline void SideScanSource::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  _impl_.id_.SetAllocated(id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SideScanSource.id)
}

// string computer_time = 2;
inline void SideScanSource::clear_computer_time() {
  _impl_.computer_time_.ClearToEmpty();
}
inline const std::string& SideScanSource::computer_time() const {
  // @@protoc_insertion_point(field_get:SideScanSource.computer_time)
  return _internal_computer_time();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SideScanSource::set_computer_time(ArgT0&& arg0, ArgT... args) {
 
 _impl_.computer_time_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SideScanSource.computer_time)
}
inline std::string* SideScanSource::mutable_computer_time() {
  std::string* _s = _internal_mutable_computer_time();
  // @@protoc_insertion_point(field_mutable:SideScanSource.computer_time)
  return _s;
}
inline const std::string& SideScanSource::_internal_computer_time() const {
  return _impl_.computer_time_.Get();
}
inline void SideScanSource::_internal_set_computer_time(const std::string& value) {
  
  _impl_.computer_time_.Set(value, GetArenaForAllocation());
}
inline std::string* SideScanSource::_internal_mutable_computer_time() {
  
  return _impl_.computer_time_.Mutable(GetArenaForAllocation());
}
inline std::string* SideScanSource::release_computer_time() {
  // @@protoc_insertion_point(field_release:SideScanSource.computer_time)
  return _impl_.computer_time_.Release();
}
inline void SideScanSource::set_allocated_computer_time(std::string* computer_time) {
  if (computer_time != nullptr) {
    
  } else {
    
  }
  _impl_.computer_time_.SetAllocated(computer_time, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.computer_time_.IsDefault()) {
    _impl_.computer_time_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SideScanSource.computer_time)
}

// string dt_time = 3;
inline void SideScanSource::clear_dt_time() {
  _impl_.dt_time_.ClearToEmpty();
}
inline const std::string& SideScanSource::dt_time() const {
  // @@protoc_insertion_point(field_get:SideScanSource.dt_time)
  return _internal_dt_time();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SideScanSource::set_dt_time(ArgT0&& arg0, ArgT... args) {
 
 _impl_.dt_time_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SideScanSource.dt_time)
}
inline std::string* SideScanSource::mutable_dt_time() {
  std::string* _s = _internal_mutable_dt_time();
  // @@protoc_insertion_point(field_mutable:SideScanSource.dt_time)
  return _s;
}
inline const std::string& SideScanSource::_internal_dt_time() const {
  return _impl_.dt_time_.Get();
}
inline void SideScanSource::_internal_set_dt_time(const std::string& value) {
  
  _impl_.dt_time_.Set(value, GetArenaForAllocation());
}
inline std::string* SideScanSource::_internal_mutable_dt_time() {
  
  return _impl_.dt_time_.Mutable(GetArenaForAllocation());
}
inline std::string* SideScanSource::release_dt_time() {
  // @@protoc_insertion_point(field_release:SideScanSource.dt_time)
  return _impl_.dt_time_.Release();
}
inline void SideScanSource::set_allocated_dt_time(std::string* dt_time) {
  if (dt_time != nullptr) {
    
  } else {
    
  }
  _impl_.dt_time_.SetAllocated(dt_time, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.dt_time_.IsDefault()) {
    _impl_.dt_time_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SideScanSource.dt_time)
}

// double longitude = 4;
inline void SideScanSource::clear_longitude() {
  _impl_.longitude_ = 0;
}
inline double SideScanSource::_internal_longitude() const {
  return _impl_.longitude_;
}
inline double SideScanSource::longitude() const {
  // @@protoc_insertion_point(field_get:SideScanSource.longitude)
  return _internal_longitude();
}
inline void SideScanSource::_internal_set_longitude(double value) {
  
  _impl_.longitude_ = value;
}
inline void SideScanSource::set_longitude(double value) {
  _internal_set_longitude(value);
  // @@protoc_insertion_point(field_set:SideScanSource.longitude)
}

// double latitude = 5;
inline void SideScanSource::clear_latitude() {
  _impl_.latitude_ = 0;
}
inline double SideScanSource::_internal_latitude() const {
  return _impl_.latitude_;
}
inline double SideScanSource::latitude() const {
  // @@protoc_insertion_point(field_get:SideScanSource.latitude)
  return _internal_latitude();
}
inline void SideScanSource::_internal_set_latitude(double value) {
  
  _impl_.latitude_ = value;
}
inline void SideScanSource::set_latitude(double value) {
  _internal_set_latitude(value);
  // @@protoc_insertion_point(field_set:SideScanSource.latitude)
}

// float dt_speed = 6;
inline void SideScanSource::clear_dt_speed() {
  _impl_.dt_speed_ = 0;
}
inline float SideScanSource::_internal_dt_speed() const {
  return _impl_.dt_speed_;
}
inline float SideScanSource::dt_speed() const {
  // @@protoc_insertion_point(field_get:SideScanSource.dt_speed)
  return _internal_dt_speed();
}
inline void SideScanSource::_internal_set_dt_speed(float value) {
  
  _impl_.dt_speed_ = value;
}
inline void SideScanSource::set_dt_speed(float value) {
  _internal_set_dt_speed(value);
  // @@protoc_insertion_point(field_set:SideScanSource.dt_speed)
}

// string horizontal_range_direction = 7;
inline void SideScanSource::clear_horizontal_range_direction() {
  _impl_.horizontal_range_direction_.ClearToEmpty();
}
inline const std::string& SideScanSource::horizontal_range_direction() const {
  // @@protoc_insertion_point(field_get:SideScanSource.horizontal_range_direction)
  return _internal_horizontal_range_direction();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SideScanSource::set_horizontal_range_direction(ArgT0&& arg0, ArgT... args) {
 
 _impl_.horizontal_range_direction_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SideScanSource.horizontal_range_direction)
}
inline std::string* SideScanSource::mutable_horizontal_range_direction() {
  std::string* _s = _internal_mutable_horizontal_range_direction();
  // @@protoc_insertion_point(field_mutable:SideScanSource.horizontal_range_direction)
  return _s;
}
inline const std::string& SideScanSource::_internal_horizontal_range_direction() const {
  return _impl_.horizontal_range_direction_.Get();
}
inline void SideScanSource::_internal_set_horizontal_range_direction(const std::string& value) {
  
  _impl_.horizontal_range_direction_.Set(value, GetArenaForAllocation());
}
inline std::string* SideScanSource::_internal_mutable_horizontal_range_direction() {
  
  return _impl_.horizontal_range_direction_.Mutable(GetArenaForAllocation());
}
inline std::string* SideScanSource::release_horizontal_range_direction() {
  // @@protoc_insertion_point(field_release:SideScanSource.horizontal_range_direction)
  return _impl_.horizontal_range_direction_.Release();
}
inline void SideScanSource::set_allocated_horizontal_range_direction(std::string* horizontal_range_direction) {
  if (horizontal_range_direction != nullptr) {
    
  } else {
    
  }
  _impl_.horizontal_range_direction_.SetAllocated(horizontal_range_direction, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.horizontal_range_direction_.IsDefault()) {
    _impl_.horizontal_range_direction_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SideScanSource.horizontal_range_direction)
}

// float horizontal_range_value = 8;
inline void SideScanSource::clear_horizontal_range_value() {
  _impl_.horizontal_range_value_ = 0;
}
inline float SideScanSource::_internal_horizontal_range_value() const {
  return _impl_.horizontal_range_value_;
}
inline float SideScanSource::horizontal_range_value() const {
  // @@protoc_insertion_point(field_get:SideScanSource.horizontal_range_value)
  return _internal_horizontal_range_value();
}
inline void SideScanSource::_internal_set_horizontal_range_value(float value) {
  
  _impl_.horizontal_range_value_ = value;
}
inline void SideScanSource::set_horizontal_range_value(float value) {
  _internal_set_horizontal_range_value(value);
  // @@protoc_insertion_point(field_set:SideScanSource.horizontal_range_value)
}

// float height_from_bottom = 9;
inline void SideScanSource::clear_height_from_bottom() {
  _impl_.height_from_bottom_ = 0;
}
inline float SideScanSource::_internal_height_from_bottom() const {
  return _impl_.height_from_bottom_;
}
inline float SideScanSource::height_from_bottom() const {
  // @@protoc_insertion_point(field_get:SideScanSource.height_from_bottom)
  return _internal_height_from_bottom();
}
inline void SideScanSource::_internal_set_height_from_bottom(float value) {
  
  _impl_.height_from_bottom_ = value;
}
inline void SideScanSource::set_height_from_bottom(float value) {
  _internal_set_height_from_bottom(value);
  // @@protoc_insertion_point(field_set:SideScanSource.height_from_bottom)
}

// float r_theat = 10;
inline void SideScanSource::clear_r_theat() {
  _impl_.r_theat_ = 0;
}
inline float SideScanSource::_internal_r_theat() const {
  return _impl_.r_theat_;
}
inline float SideScanSource::r_theat() const {
  // @@protoc_insertion_point(field_get:SideScanSource.r_theat)
  return _internal_r_theat();
}
inline void SideScanSource::_internal_set_r_theat(float value) {
  
  _impl_.r_theat_ = value;
}
inline void SideScanSource::set_r_theat(float value) {
  _internal_set_r_theat(value);
  // @@protoc_insertion_point(field_set:SideScanSource.r_theat)
}

// string side_scan_image_name = 11;
inline void SideScanSource::clear_side_scan_image_name() {
  _impl_.side_scan_image_name_.ClearToEmpty();
}
inline const std::string& SideScanSource::side_scan_image_name() const {
  // @@protoc_insertion_point(field_get:SideScanSource.side_scan_image_name)
  return _internal_side_scan_image_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SideScanSource::set_side_scan_image_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.side_scan_image_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SideScanSource.side_scan_image_name)
}
inline std::string* SideScanSource::mutable_side_scan_image_name() {
  std::string* _s = _internal_mutable_side_scan_image_name();
  // @@protoc_insertion_point(field_mutable:SideScanSource.side_scan_image_name)
  return _s;
}
inline const std::string& SideScanSource::_internal_side_scan_image_name() const {
  return _impl_.side_scan_image_name_.Get();
}
inline void SideScanSource::_internal_set_side_scan_image_name(const std::string& value) {
  
  _impl_.side_scan_image_name_.Set(value, GetArenaForAllocation());
}
inline std::string* SideScanSource::_internal_mutable_side_scan_image_name() {
  
  return _impl_.side_scan_image_name_.Mutable(GetArenaForAllocation());
}
inline std::string* SideScanSource::release_side_scan_image_name() {
  // @@protoc_insertion_point(field_release:SideScanSource.side_scan_image_name)
  return _impl_.side_scan_image_name_.Release();
}
inline void SideScanSource::set_allocated_side_scan_image_name(std::string* side_scan_image_name) {
  if (side_scan_image_name != nullptr) {
    
  } else {
    
  }
  _impl_.side_scan_image_name_.SetAllocated(side_scan_image_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.side_scan_image_name_.IsDefault()) {
    _impl_.side_scan_image_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SideScanSource.side_scan_image_name)
}

// float along_track = 12;
inline void SideScanSource::clear_along_track() {
  _impl_.along_track_ = 0;
}
inline float SideScanSource::_internal_along_track() const {
  return _impl_.along_track_;
}
inline float SideScanSource::along_track() const {
  // @@protoc_insertion_point(field_get:SideScanSource.along_track)
  return _internal_along_track();
}
inline void SideScanSource::_internal_set_along_track(float value) {
  
  _impl_.along_track_ = value;
}
inline void SideScanSource::set_along_track(float value) {
  _internal_set_along_track(value);
  // @@protoc_insertion_point(field_set:SideScanSource.along_track)
}

// float across_track = 13;
inline void SideScanSource::clear_across_track() {
  _impl_.across_track_ = 0;
}
inline float SideScanSource::_internal_across_track() const {
  return _impl_.across_track_;
}
inline float SideScanSource::across_track() const {
  // @@protoc_insertion_point(field_get:SideScanSource.across_track)
  return _internal_across_track();
}
inline void SideScanSource::_internal_set_across_track(float value) {
  
  _impl_.across_track_ = value;
}
inline void SideScanSource::set_across_track(float value) {
  _internal_set_across_track(value);
  // @@protoc_insertion_point(field_set:SideScanSource.across_track)
}

// string remarks = 14;
inline void SideScanSource::clear_remarks() {
  _impl_.remarks_.ClearToEmpty();
}
inline const std::string& SideScanSource::remarks() const {
  // @@protoc_insertion_point(field_get:SideScanSource.remarks)
  return _internal_remarks();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SideScanSource::set_remarks(ArgT0&& arg0, ArgT... args) {
 
 _impl_.remarks_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SideScanSource.remarks)
}
inline std::string* SideScanSource::mutable_remarks() {
  std::string* _s = _internal_mutable_remarks();
  // @@protoc_insertion_point(field_mutable:SideScanSource.remarks)
  return _s;
}
inline const std::string& SideScanSource::_internal_remarks() const {
  return _impl_.remarks_.Get();
}
inline void SideScanSource::_internal_set_remarks(const std::string& value) {
  
  _impl_.remarks_.Set(value, GetArenaForAllocation());
}
inline std::string* SideScanSource::_internal_mutable_remarks() {
  
  return _impl_.remarks_.Mutable(GetArenaForAllocation());
}
inline std::string* SideScanSource::release_remarks() {
  // @@protoc_insertion_point(field_release:SideScanSource.remarks)
  return _impl_.remarks_.Release();
}
inline void SideScanSource::set_allocated_remarks(std::string* remarks) {
  if (remarks != nullptr) {
    
  } else {
    
  }
  _impl_.remarks_.SetAllocated(remarks, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.remarks_.IsDefault()) {
    _impl_.remarks_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SideScanSource.remarks)
}

// float suppose_size = 15;
inline void SideScanSource::clear_suppose_size() {
  _impl_.suppose_size_ = 0;
}
inline float SideScanSource::_internal_suppose_size() const {
  return _impl_.suppose_size_;
}
inline float SideScanSource::suppose_size() const {
  // @@protoc_insertion_point(field_get:SideScanSource.suppose_size)
  return _internal_suppose_size();
}
inline void SideScanSource::_internal_set_suppose_size(float value) {
  
  _impl_.suppose_size_ = value;
}
inline void SideScanSource::set_suppose_size(float value) {
  _internal_set_suppose_size(value);
  // @@protoc_insertion_point(field_set:SideScanSource.suppose_size)
}

// uint32 priority = 16;
inline void SideScanSource::clear_priority() {
  _impl_.priority_ = 0u;
}
inline uint32_t SideScanSource::_internal_priority() const {
  return _impl_.priority_;
}
inline uint32_t SideScanSource::priority() const {
  // @@protoc_insertion_point(field_get:SideScanSource.priority)
  return _internal_priority();
}
inline void SideScanSource::_internal_set_priority(uint32_t value) {
  
  _impl_.priority_ = value;
}
inline void SideScanSource::set_priority(uint32_t value) {
  _internal_set_priority(value);
  // @@protoc_insertion_point(field_set:SideScanSource.priority)
}

// string verify_image_paths = 17;
inline void SideScanSource::clear_verify_image_paths() {
  _impl_.verify_image_paths_.ClearToEmpty();
}
inline const std::string& SideScanSource::verify_image_paths() const {
  // @@protoc_insertion_point(field_get:SideScanSource.verify_image_paths)
  return _internal_verify_image_paths();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SideScanSource::set_verify_image_paths(ArgT0&& arg0, ArgT... args) {
 
 _impl_.verify_image_paths_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SideScanSource.verify_image_paths)
}
inline std::string* SideScanSource::mutable_verify_image_paths() {
  std::string* _s = _internal_mutable_verify_image_paths();
  // @@protoc_insertion_point(field_mutable:SideScanSource.verify_image_paths)
  return _s;
}
inline const std::string& SideScanSource::_internal_verify_image_paths() const {
  return _impl_.verify_image_paths_.Get();
}
inline void SideScanSource::_internal_set_verify_image_paths(const std::string& value) {
  
  _impl_.verify_image_paths_.Set(value, GetArenaForAllocation());
}
inline std::string* SideScanSource::_internal_mutable_verify_image_paths() {
  
  return _impl_.verify_image_paths_.Mutable(GetArenaForAllocation());
}
inline std::string* SideScanSource::release_verify_image_paths() {
  // @@protoc_insertion_point(field_release:SideScanSource.verify_image_paths)
  return _impl_.verify_image_paths_.Release();
}
inline void SideScanSource::set_allocated_verify_image_paths(std::string* verify_image_paths) {
  if (verify_image_paths != nullptr) {
    
  } else {
    
  }
  _impl_.verify_image_paths_.SetAllocated(verify_image_paths, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.verify_image_paths_.IsDefault()) {
    _impl_.verify_image_paths_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SideScanSource.verify_image_paths)
}

// string image_description = 18;
inline void SideScanSource::clear_image_description() {
  _impl_.image_description_.ClearToEmpty();
}
inline const std::string& SideScanSource::image_description() const {
  // @@protoc_insertion_point(field_get:SideScanSource.image_description)
  return _internal_image_description();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SideScanSource::set_image_description(ArgT0&& arg0, ArgT... args) {
 
 _impl_.image_description_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SideScanSource.image_description)
}
inline std::string* SideScanSource::mutable_image_description() {
  std::string* _s = _internal_mutable_image_description();
  // @@protoc_insertion_point(field_mutable:SideScanSource.image_description)
  return _s;
}
inline const std::string& SideScanSource::_internal_image_description() const {
  return _impl_.image_description_.Get();
}
inline void SideScanSource::_internal_set_image_description(const std::string& value) {
  
  _impl_.image_description_.Set(value, GetArenaForAllocation());
}
inline std::string* SideScanSource::_internal_mutable_image_description() {
  
  return _impl_.image_description_.Mutable(GetArenaForAllocation());
}
inline std::string* SideScanSource::release_image_description() {
  // @@protoc_insertion_point(field_release:SideScanSource.image_description)
  return _impl_.image_description_.Release();
}
inline void SideScanSource::set_allocated_image_description(std::string* image_description) {
  if (image_description != nullptr) {
    
  } else {
    
  }
  _impl_.image_description_.SetAllocated(image_description, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.image_description_.IsDefault()) {
    _impl_.image_description_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SideScanSource.image_description)
}

// double target_longitude = 19;
inline void SideScanSource::clear_target_longitude() {
  _impl_.target_longitude_ = 0;
}
inline double SideScanSource::_internal_target_longitude() const {
  return _impl_.target_longitude_;
}
inline double SideScanSource::target_longitude() const {
  // @@protoc_insertion_point(field_get:SideScanSource.target_longitude)
  return _internal_target_longitude();
}
inline void SideScanSource::_internal_set_target_longitude(double value) {
  
  _impl_.target_longitude_ = value;
}
inline void SideScanSource::set_target_longitude(double value) {
  _internal_set_target_longitude(value);
  // @@protoc_insertion_point(field_set:SideScanSource.target_longitude)
}

// double target_latitude = 20;
inline void SideScanSource::clear_target_latitude() {
  _impl_.target_latitude_ = 0;
}
inline double SideScanSource::_internal_target_latitude() const {
  return _impl_.target_latitude_;
}
inline double SideScanSource::target_latitude() const {
  // @@protoc_insertion_point(field_get:SideScanSource.target_latitude)
  return _internal_target_latitude();
}
inline void SideScanSource::_internal_set_target_latitude(double value) {
  
  _impl_.target_latitude_ = value;
}
inline void SideScanSource::set_target_latitude(double value) {
  _internal_set_target_latitude(value);
  // @@protoc_insertion_point(field_set:SideScanSource.target_latitude)
}

// float position_error = 21;
inline void SideScanSource::clear_position_error() {
  _impl_.position_error_ = 0;
}
inline float SideScanSource::_internal_position_error() const {
  return _impl_.position_error_;
}
inline float SideScanSource::position_error() const {
  // @@protoc_insertion_point(field_get:SideScanSource.position_error)
  return _internal_position_error();
}
inline void SideScanSource::_internal_set_position_error(float value) {
  
  _impl_.position_error_ = value;
}
inline void SideScanSource::set_position_error(float value) {
  _internal_set_position_error(value);
  // @@protoc_insertion_point(field_set:SideScanSource.position_error)
}

// string cruise_number = 22;
inline void SideScanSource::clear_cruise_number() {
  _impl_.cruise_number_.ClearToEmpty();
}
inline const std::string& SideScanSource::cruise_number() const {
  // @@protoc_insertion_point(field_get:SideScanSource.cruise_number)
  return _internal_cruise_number();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SideScanSource::set_cruise_number(ArgT0&& arg0, ArgT... args) {
 
 _impl_.cruise_number_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SideScanSource.cruise_number)
}
inline std::string* SideScanSource::mutable_cruise_number() {
  std::string* _s = _internal_mutable_cruise_number();
  // @@protoc_insertion_point(field_mutable:SideScanSource.cruise_number)
  return _s;
}
inline const std::string& SideScanSource::_internal_cruise_number() const {
  return _impl_.cruise_number_.Get();
}
inline void SideScanSource::_internal_set_cruise_number(const std::string& value) {
  
  _impl_.cruise_number_.Set(value, GetArenaForAllocation());
}
inline std::string* SideScanSource::_internal_mutable_cruise_number() {
  
  return _impl_.cruise_number_.Mutable(GetArenaForAllocation());
}
inline std::string* SideScanSource::release_cruise_number() {
  // @@protoc_insertion_point(field_release:SideScanSource.cruise_number)
  return _impl_.cruise_number_.Release();
}
inline void SideScanSource::set_allocated_cruise_number(std::string* cruise_number) {
  if (cruise_number != nullptr) {
    
  } else {
    
  }
  _impl_.cruise_number_.SetAllocated(cruise_number, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.cruise_number_.IsDefault()) {
    _impl_.cruise_number_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SideScanSource.cruise_number)
}

// string dive_number = 23;
inline void SideScanSource::clear_dive_number() {
  _impl_.dive_number_.ClearToEmpty();
}
inline const std::string& SideScanSource::dive_number() const {
  // @@protoc_insertion_point(field_get:SideScanSource.dive_number)
  return _internal_dive_number();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SideScanSource::set_dive_number(ArgT0&& arg0, ArgT... args) {
 
 _impl_.dive_number_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SideScanSource.dive_number)
}
inline std::string* SideScanSource::mutable_dive_number() {
  std::string* _s = _internal_mutable_dive_number();
  // @@protoc_insertion_point(field_mutable:SideScanSource.dive_number)
  return _s;
}
inline const std::string& SideScanSource::_internal_dive_number() const {
  return _impl_.dive_number_.Get();
}
inline void SideScanSource::_internal_set_dive_number(const std::string& value) {
  
  _impl_.dive_number_.Set(value, GetArenaForAllocation());
}
inline std::string* SideScanSource::_internal_mutable_dive_number() {
  
  return _impl_.dive_number_.Mutable(GetArenaForAllocation());
}
inline std::string* SideScanSource::release_dive_number() {
  // @@protoc_insertion_point(field_release:SideScanSource.dive_number)
  return _impl_.dive_number_.Release();
}
inline void SideScanSource::set_allocated_dive_number(std::string* dive_number) {
  if (dive_number != nullptr) {
    
  } else {
    
  }
  _impl_.dive_number_.SetAllocated(dive_number, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.dive_number_.IsDefault()) {
    _impl_.dive_number_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SideScanSource.dive_number)
}

// uint32 status = 24;
inline void SideScanSource::clear_status() {
  _impl_.status_ = 0u;
}
inline uint32_t SideScanSource::_internal_status() const {
  return _impl_.status_;
}
inline uint32_t SideScanSource::status() const {
  // @@protoc_insertion_point(field_get:SideScanSource.status)
  return _internal_status();
}
inline void SideScanSource::_internal_set_status(uint32_t value) {
  
  _impl_.status_ = value;
}
inline void SideScanSource::set_status(uint32_t value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:SideScanSource.status)
}

// -------------------------------------------------------------------

// SideScanSourceList

// repeated .SideScanSource list = 1;
inline int SideScanSourceList::_internal_list_size() const {
  return _impl_.list_.size();
}
inline int SideScanSourceList::list_size() const {
  return _internal_list_size();
}
inline void SideScanSourceList::clear_list() {
  _impl_.list_.Clear();
}
inline ::SideScanSource* SideScanSourceList::mutable_list(int index) {
  // @@protoc_insertion_point(field_mutable:SideScanSourceList.list)
  return _impl_.list_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SideScanSource >*
SideScanSourceList::mutable_list() {
  // @@protoc_insertion_point(field_mutable_list:SideScanSourceList.list)
  return &_impl_.list_;
}
inline const ::SideScanSource& SideScanSourceList::_internal_list(int index) const {
  return _impl_.list_.Get(index);
}
inline const ::SideScanSource& SideScanSourceList::list(int index) const {
  // @@protoc_insertion_point(field_get:SideScanSourceList.list)
  return _internal_list(index);
}
inline ::SideScanSource* SideScanSourceList::_internal_add_list() {
  return _impl_.list_.Add();
}
inline ::SideScanSource* SideScanSourceList::add_list() {
  ::SideScanSource* _add = _internal_add_list();
  // @@protoc_insertion_point(field_add:SideScanSourceList.list)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SideScanSource >&
SideScanSourceList::list() const {
  // @@protoc_insertion_point(field_list:SideScanSourceList.list)
  return _impl_.list_;
}

// -------------------------------------------------------------------

// StatusResponse

// bool status = 1;
inline void StatusResponse::clear_status() {
  _impl_.status_ = false;
}
inline bool StatusResponse::_internal_status() const {
  return _impl_.status_;
}
inline bool StatusResponse::status() const {
  // @@protoc_insertion_point(field_get:StatusResponse.status)
  return _internal_status();
}
inline void StatusResponse::_internal_set_status(bool value) {
  
  _impl_.status_ = value;
}
inline void StatusResponse::set_status(bool value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:StatusResponse.status)
}

// string message = 2;
inline void StatusResponse::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& StatusResponse::message() const {
  // @@protoc_insertion_point(field_get:StatusResponse.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StatusResponse::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:StatusResponse.message)
}
inline std::string* StatusResponse::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:StatusResponse.message)
  return _s;
}
inline const std::string& StatusResponse::_internal_message() const {
  return _impl_.message_.Get();
}
inline void StatusResponse::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* StatusResponse::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* StatusResponse::release_message() {
  // @@protoc_insertion_point(field_release:StatusResponse.message)
  return _impl_.message_.Release();
}
inline void StatusResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:StatusResponse.message)
}

// -------------------------------------------------------------------

// CruiseRouteSource

// string cruise = 1;
inline void CruiseRouteSource::clear_cruise() {
  _impl_.cruise_.ClearToEmpty();
}
inline const std::string& CruiseRouteSource::cruise() const {
  // @@protoc_insertion_point(field_get:CruiseRouteSource.cruise)
  return _internal_cruise();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CruiseRouteSource::set_cruise(ArgT0&& arg0, ArgT... args) {
 
 _impl_.cruise_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:CruiseRouteSource.cruise)
}
inline std::string* CruiseRouteSource::mutable_cruise() {
  std::string* _s = _internal_mutable_cruise();
  // @@protoc_insertion_point(field_mutable:CruiseRouteSource.cruise)
  return _s;
}
inline const std::string& CruiseRouteSource::_internal_cruise() const {
  return _impl_.cruise_.Get();
}
inline void CruiseRouteSource::_internal_set_cruise(const std::string& value) {
  
  _impl_.cruise_.Set(value, GetArenaForAllocation());
}
inline std::string* CruiseRouteSource::_internal_mutable_cruise() {
  
  return _impl_.cruise_.Mutable(GetArenaForAllocation());
}
inline std::string* CruiseRouteSource::release_cruise() {
  // @@protoc_insertion_point(field_release:CruiseRouteSource.cruise)
  return _impl_.cruise_.Release();
}
inline void CruiseRouteSource::set_allocated_cruise(std::string* cruise) {
  if (cruise != nullptr) {
    
  } else {
    
  }
  _impl_.cruise_.SetAllocated(cruise, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.cruise_.IsDefault()) {
    _impl_.cruise_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:CruiseRouteSource.cruise)
}

// string type = 2;
inline void CruiseRouteSource::clear_type() {
  _impl_.type_.ClearToEmpty();
}
inline const std::string& CruiseRouteSource::type() const {
  // @@protoc_insertion_point(field_get:CruiseRouteSource.type)
  return _internal_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CruiseRouteSource::set_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:CruiseRouteSource.type)
}
inline std::string* CruiseRouteSource::mutable_type() {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:CruiseRouteSource.type)
  return _s;
}
inline const std::string& CruiseRouteSource::_internal_type() const {
  return _impl_.type_.Get();
}
inline void CruiseRouteSource::_internal_set_type(const std::string& value) {
  
  _impl_.type_.Set(value, GetArenaForAllocation());
}
inline std::string* CruiseRouteSource::_internal_mutable_type() {
  
  return _impl_.type_.Mutable(GetArenaForAllocation());
}
inline std::string* CruiseRouteSource::release_type() {
  // @@protoc_insertion_point(field_release:CruiseRouteSource.type)
  return _impl_.type_.Release();
}
inline void CruiseRouteSource::set_allocated_type(std::string* type) {
  if (type != nullptr) {
    
  } else {
    
  }
  _impl_.type_.SetAllocated(type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.type_.IsDefault()) {
    _impl_.type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:CruiseRouteSource.type)
}

// string name = 3;
inline void CruiseRouteSource::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& CruiseRouteSource::name() const {
  // @@protoc_insertion_point(field_get:CruiseRouteSource.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CruiseRouteSource::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:CruiseRouteSource.name)
}
inline std::string* CruiseRouteSource::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:CruiseRouteSource.name)
  return _s;
}
inline const std::string& CruiseRouteSource::_internal_name() const {
  return _impl_.name_.Get();
}
inline void CruiseRouteSource::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* CruiseRouteSource::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* CruiseRouteSource::release_name() {
  // @@protoc_insertion_point(field_release:CruiseRouteSource.name)
  return _impl_.name_.Release();
}
inline void CruiseRouteSource::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:CruiseRouteSource.name)
}

// -------------------------------------------------------------------

// CruiseRouteSourceList

// repeated .CruiseRouteSource list = 1;
inline int CruiseRouteSourceList::_internal_list_size() const {
  return _impl_.list_.size();
}
inline int CruiseRouteSourceList::list_size() const {
  return _internal_list_size();
}
inline void CruiseRouteSourceList::clear_list() {
  _impl_.list_.Clear();
}
inline ::CruiseRouteSource* CruiseRouteSourceList::mutable_list(int index) {
  // @@protoc_insertion_point(field_mutable:CruiseRouteSourceList.list)
  return _impl_.list_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CruiseRouteSource >*
CruiseRouteSourceList::mutable_list() {
  // @@protoc_insertion_point(field_mutable_list:CruiseRouteSourceList.list)
  return &_impl_.list_;
}
inline const ::CruiseRouteSource& CruiseRouteSourceList::_internal_list(int index) const {
  return _impl_.list_.Get(index);
}
inline const ::CruiseRouteSource& CruiseRouteSourceList::list(int index) const {
  // @@protoc_insertion_point(field_get:CruiseRouteSourceList.list)
  return _internal_list(index);
}
inline ::CruiseRouteSource* CruiseRouteSourceList::_internal_add_list() {
  return _impl_.list_.Add();
}
inline ::CruiseRouteSource* CruiseRouteSourceList::add_list() {
  ::CruiseRouteSource* _add = _internal_add_list();
  // @@protoc_insertion_point(field_add:CruiseRouteSourceList.list)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CruiseRouteSource >&
CruiseRouteSourceList::list() const {
  // @@protoc_insertion_point(field_list:CruiseRouteSourceList.list)
  return _impl_.list_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sidescansource_2eproto
